### ISSUE TITLE
fix `getCharWidth`

### ISSUE THREAD

**Issue by decioferreira** [guida-lang/compiler#14]
Currently the implementation of `Parse.Primitives.getCharWidth` is very poor. We need to fix it.

One of the current issue shows up when trying to compile `examples/src/HttpQuotes.elm`:

```
% cd examples
% % guida make src/HttpQuotes.elm                 
Compiled in DEBUG mode. Follow the advice at https://elm-lang.org/0.19.1/optimize for better performance and smaller assets.
Detected problems in 1 module.
-- ENDLESS STRING ------------------------------------------ /src/HttpQuotes.elm

I got to the end of the line without seeing the closing double quote:

115|                     [ text "— "

                                  ^

Strings look like "this" with double quotes on each end. Is the closing double quote missing in your code?

Note: For a string that spans multiple lines, you can use the multi-line string syntax like this:

    """

    # Multi-line Strings

    

    - start with triple double quotes

    - write whatever you want

    - no need to escape newlines or double quotes

    - end with triple double quotes

    """

```

**Comment by decioferreira** [comment]
miniBill/elm-unicode#3 might have the solution for this

**Comment by MartinSStewart** [comment]
The fact that `getCharWidth '❤'` returns 1 while `getCharWidth '🌈'` returns leaves me stumped. Maybe we need a script that just tries each unicode char until we have enough examples that a pattern emerges.

**Comment by decioferreira** [comment]
There must some issue somewhere else on the code, because if I try to parse this `🙈` on https://github.com/elm/core/blob/1.0.5/src/Char.elm#L44 it gives me `NaN` on `getCharWidth`, but when trying it separately, it seems to work fine. Running the following on https://elm-lang.org/try:

```
import Html exposing (text)


main =
  text (Debug.toString (Char.toCode '🙈'))
```

Returns `128584`

**Comment by decioferreira** [comment]
finally found the fix for this one, the issue related to elm/core#977. `Parse.Primitives. unsafeIndex` and elm-tests have been updated as part of this change.
